version: '3.7'

services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:6.2
        network_mode: 18series
        environment:
            PGADMIN_DEFAULT_EMAIL: sajibma@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 123456
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - 5050:80
        restart: unless-stopped
volumes: 
    pgadmin: