version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./code:/code
      - ./config/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - 18series
    ports:
      - "8185:80"
      - "8186:8186"
    links:
      - php
    depends_on:
      - php
  php:
    container_name: php74
    image: php:7.4.0-fpm
    volumes:
      - ./code:/code
    networks:
      - 18series
    ports:
      - "9000:9000"
networks:
  18series:
    external: true
    driver: bridge
