version: "3.7"
services:
  server:
    image: mysql:5.7
    container_name: mysql
    network_mode: 18series
    ports:
      - 3306:3306
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: musfek
      MYSQL_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql